#!/bin/bash

ANIM="$1"
DUR="$2"
CLASS="$3"

STATEFILE="$XDG_RUNTIME_DIR/ewwii_calendar_popup_state"

if [[ -f $STATEFILE ]]; then
  last_state=$(cat $STATEFILE)
else
  last_state="closed"
fi

if [[ $last_state == "open" ]]; then
  echo "closed" >$STATEFILE
  scripts/close_with_anim "calendar_popup" "$ANIM" "$DUR" "$CLASS"
else
  ewwii open calendar_popup --screen 0 --config .
  echo "open" >$STATEFILE
fi
sleep 0.2
